### ISSUE TITLE
Flask: Decrease verbosity of logs

### ISSUE THREAD

**Issue by cklamann** [ccmbioinfo/stager#905]
- ~~remove debugging info statements wherever possible~~
- [ ] perform a brief "audit" of existing logs/logging statements in order to help team arrive at a standard for future development. What existing logs are useful? Which are extraneous? What is/should be the difference between 'debug' and 'info'?
- [ ] update logs to reflect new standards
- [ ] allow SQLAlchemy logs to be disabled with an env variable

**Comment by kevinlul** [comment]
Sidecar logging proof-of-concept with a FIFO/named pipe:

```yaml
version: "3.9"
services:
  primary:
    image: ubuntu:20.04
    command: bash -c 'set -euo pipefail;
      if [[ ! -p /var/log/app/logs.fifo ]]; then
         mkfifo /var/log/app/logs.fifo;
      fi;
      while true; do
        date -Is > /var/log/app/logs.fifo;
        echo `date -Is` Hello;
        sleep 5;
      done'
    volumes:
      - logs:/var/log/app
  sidecar:
    image: ubuntu:20.04
    command: tail -f /var/log/app/logs.fifo
    volumes:
      - logs:/var/log/app
    depends_on:
      - primary
volumes:
  logs:
```
